


##text = "360 GRADER få den beste servicen fra ditt treningssenter. Både når du trener på og utenfor sentret. Helt nytt utseende med tre hovedområder: SENTER OMRÅDE: Finn hvilke tjenester sentret tilbyr og velg de som interesserer deg. MIN AKTIVITET: Hva du har valgt å gjøre: Her finner du ditt treningsprogram, gruppetimer du har booket deg på, utfordringer du deltar i og andre aktiviteter du har valgt å gjøre på sentret. RESULTATER: Se din loggbok, resultater og progresjon.Tren med 360 GRADER for å samle dine MOVEs og bli mer aktiv for hver dag som går. Få den beste opplevelsen på Technogym utstyr ved å logge deg inn med Bluetooth eller QR koden via 360 GRADER. Utstyret vil automatisk starte ditt program og dine resultater vil automatisk bli logget på din MyWellness konto. Logg MOVEs manuelt eller synkroniser med andre apper som Apple Health, Fitbit, Garmin, MapMyFitness, MyFitnessPal, Polar, RunKeeper, Strava, Swimtag and Withings.---------------------------------HVORFOR BRUKE 360 GRADER?SENTERETS TJENESTER LETT: Via SENTRETS OMRÅDE finner du programmer, gruppetimer og utfordringer sentret tilbyr. EN VIRITUEL TRENER SOM HJELPER DEG MED DIN TRENING: Velg enkelt hvilken treningsøkt du vil utføre i dag inne på MINE AKTIVITETER siden og la appen veiled deg gjennom økten: Appen går automatisk videre til neste øvelse og gir deg muligheten til å rangere din trening og planlegge din neste treningsøkt.PROGRAM: Få ditt skreddersydde og komplette treningsprogram med kondisjons, styrke, gruppetimer og alle andre type aktiviteter; alle øvelsene har tilhørende bilde og video; hold oversikt over dine resultater automatisk ved å logge deg inn på Technogym utstyr, uansett hvor du er i verden.  DEN ULTIMATE GRUPPETIME OPPLEVELSEN: Bruk 360 GRADER for å enkelt finne de timene som interesserer deg og book deg på timen. Du vil motta påminnelser som hjelper deg med å huske timen. UTENDØRS AKTIVITETER: Hold oversikt over dine aktiviteter som gjøres utenfor sentret via 360 GRADER ved å loggføre disse manuelt eller ved å automatisk overføre aktiviteter som utføres via andre apper som Apple Health, Fitbit, Garmin, MapMyFitness, MyFitnessPal, Polar, RunKeeper, Strava, Swimtag and WithingsENGASJERENDE: Bli med på utfordringer som ditt senter organiserer. Bli motivert ved å trene og forbedre din posisjon på resultatlisten som alltid er oppdatertKROPPSMÅL: Hold oversikt over dine kroppsmål (Vekt, BMI, FTP verdier m.m), se din framgang over tid."

##t<- gsub('[^\x20-\x7E]', '', y)

##t


df<- read.csv(TABELLAFINALE)                                         #Apri tabella finale prendi quinta colonna con descrizioni ed elimina non-ASCII
df[,5]<-lapply(df[,5], function(x) gsub('[^\x20-\x7E]', '', x))
